import { useEffect, useState } from "react";
import { Icon } from "semantic-ui-react";
import { usePlaylist } from "../../utils/playlist";
import SpotifyButton from "../button/button";
import ModalPlaylist from "../modal-create-playlist";
import MusicCard from "../music-card";
import toast from "react-hot-toast";
import { Auth } from "../../utils/auth";
import { useTracklist } from "../../utils/Tracklist";
import { useDispatch } from "react-redux";
import { clearList, storeTracklist } from "../../store/tracklist";
import { getTopTracks } from "../../utils/spotify";